# Generated by Django 6.0.2 on 2026-02-13 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_profile_name_profile_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.skillpost'),
        ),
    ]
